#####
#### pyhmmer ####
# Kosta is working on converting the hhsuite DB to pyhmmer format.
# regardless I know the code works on pyhmmer (due to the subset db)

#### envhog ####
# use the default from the download 

#### mmseqs2 ####

conda activate megapharokka_env 

# create the mmseqs2 db from the consensus file generated by Mike
mmseqs createdb EnVhog.consensus.fasta EnVhog_consensus

